module.exports = {
    // Client -> Server
    CLIENT_EVENTS: {
        JOIN_QUEUE: 'JOIN_QUEUE',
        LEAVE_QUEUE: 'LEAVE_QUEUE',
        JOIN_ROOM: 'JOIN_ROOM',
        READY: 'READY',
        CHOOSE_MATCH_SETTING: 'CHOOSE_MATCH_SETTING',
        BAIL_OUT: 'BAIL_OUT',
        PING: 'PING',

        // Challenge & Private Lobby
        SEND_CHALLENGE: 'SEND_CHALLENGE',
        RESPOND_CHALLENGE: 'RESPOND_CHALLENGE',
        CANCEL_CHALLENGE: 'CANCEL_CHALLENGE',
        JOIN_LOBBY: 'JOIN_LOBBY',
        UPDATE_LOBBY_SETTINGS: 'UPDATE_LOBBY_SETTINGS',
        TOGGLE_LOBBY_READY: 'TOGGLE_LOBBY_READY',
        SEND_LOBBY_MESSAGE: 'SEND_LOBBY_MESSAGE',
        LEAVE_LOBBY: 'LEAVE_LOBBY',
        START_LOBBY_MATCH: 'START_LOBBY_MATCH'
    },
    // Server -> Client
    SERVER_EVENTS: {
        QUEUE_JOINED: 'QUEUE_JOINED',
        QUEUE_LEFT: 'QUEUE_LEFT',
        MATCH_FOUND: 'MATCH_FOUND',
        ROOM_CREATED: 'ROOM_CREATED',
        ROOM_JOINED: 'ROOM_JOINED',
        MATCH_SETUP_STARTED: 'MATCH_SETUP_STARTED',
        MATCH_SETTING_CHOSEN: 'MATCH_SETTING_CHOSEN',
        MATCH_SETUP_COMPLETED: 'MATCH_SETUP_COMPLETED',
        COUNTDOWN_STARTED: 'COUNTDOWN_STARTED',
        CONTEST_STARTED: 'CONTEST_STARTED',
        PLAYER_SUBMITTED: 'PLAYER_SUBMITTED',
        SCORE_UPDATED: 'SCORE_UPDATED',
        MATCH_FINISHED: 'MATCH_FINISHED',
        PLAYER_DISCONNECTED: 'PLAYER_DISCONNECTED',
        PLAYER_RECONNECTED: 'PLAYER_RECONNECTED',
        ERROR: 'ERROR',

        // Challenge & Private Lobby
        CHALLENGE_INVITE_RECEIVED: 'CHALLENGE_INVITE_RECEIVED',
        CHALLENGE_INVITE_SENT: 'CHALLENGE_INVITE_SENT',
        CHALLENGE_ACCEPTED: 'CHALLENGE_ACCEPTED',
        CHALLENGE_DECLINED: 'CHALLENGE_DECLINED',
        CHALLENGE_CANCELLED: 'CHALLENGE_CANCELLED',
        LOBBY_UPDATED: 'LOBBY_UPDATED',
        LOBBY_MESSAGE_RECEIVED: 'LOBBY_MESSAGE_RECEIVED',
        LOBBY_MATCH_STARTING: 'LOBBY_MATCH_STARTING',
        LOBBY_DISBANDED: 'LOBBY_DISBANDED',
        FRIEND_PRESENCE_UPDATED: 'FRIEND_PRESENCE_UPDATED'
    }
};
