module.exports = {
    // Client -> Server
    CLIENT_EVENTS: {
        JOIN_QUEUE: 'JOIN_QUEUE',
        LEAVE_QUEUE: 'LEAVE_QUEUE',
        JOIN_ROOM: 'JOIN_ROOM',
        READY: 'READY',
        CHOOSE_MATCH_SETTING: 'CHOOSE_MATCH_SETTING',
        BAIL_OUT: 'BAIL_OUT',
        PING: 'PING'
    },
    // Server -> Client
    SERVER_EVENTS: {
        QUEUE_JOINED: 'QUEUE_JOINED',
        QUEUE_LEFT: 'QUEUE_LEFT',
        MATCH_FOUND: 'MATCH_FOUND',
        ROOM_CREATED: 'ROOM_CREATED',
        ROOM_JOINED: 'ROOM_JOINED',
        MATCH_SETUP_STARTED: 'MATCH_SETUP_STARTED',
        MATCH_SETTING_CHOSEN: 'MATCH_SETTING_CHOSEN',
        MATCH_SETUP_COMPLETED: 'MATCH_SETUP_COMPLETED',
        COUNTDOWN_STARTED: 'COUNTDOWN_STARTED',
        CONTEST_STARTED: 'CONTEST_STARTED',
        PLAYER_SUBMITTED: 'PLAYER_SUBMITTED',
        SCORE_UPDATED: 'SCORE_UPDATED',
        MATCH_FINISHED: 'MATCH_FINISHED',
        PLAYER_DISCONNECTED: 'PLAYER_DISCONNECTED',
        PLAYER_RECONNECTED: 'PLAYER_RECONNECTED',
        ERROR: 'ERROR'
    }
};
